### PR TITLE
Loss Mean Squared Logarithmic error.

### PR DESCRIPTION
**Pull request by abhinavsp0730**
- [X] Added loss

- [x]  Added test cases

- [x]  Formatted the code with black

- [x]  Added the documention

### CODE REVIEW

**Comment by abhinavsp0730** [comment]
Hi, @charlielito please review.
Thanks

**Review by charlielito — CHANGES_REQUESTED** [review]
Looks really good!

Only one thing, from now on we are making the tests also comparing with tensorflow's implementation like in this test: https://github.com/poets-ai/elegy/blob/master/elegy/losses/binary_crossentropy_test.py#L36

Also we made today some changes to the auto docs, please run again `bash scripts/run-docs.sh`

**Comment by abhinavsp0730** [comment]
Hy, @charlielito  I've done all the changes requested by you. Would you please review again. Thanks.

**Review by charlielito — APPROVED** [review]
LGTM

**Pull request merged**
