### PR TITLE
Implemented BinaryCrossentropy metric

### PR DESCRIPTION
**Pull request by sebasarango1180**
**Updates:**

- Created BinaryCrossentropy metric
- Created basic tests for BinaryCrossentropy metric (passing)
- Created docs for BinaryCrossentropy metric
- Refactored main docs by balancing files and correcting language typos

### CODE REVIEW

**Comment by sebasarango1180** [comment]
**Note:** when reviewing conflicts, bold text belongs to my uploaded branch. 
Please let me know if you approve these writing fixes, so I can resolve the conflicting texts.
Besides, let me know if there is any comment on the BCE metric implementation.
:+1:

**Comment by charlielito** [comment]
This looks good!
@cgarciae 
Just wondering what's the difference of having this as a Metric? Because @sebasarango1180 already implemented it as a loss. And the way elegy works, it logs already each loss separately, for example when it returns all losses and metrics as a `History` object. Tensorboard also will log the each loss.

**Comment by cgarciae** [comment]
@charlielito metrics are cumulative while losses are not.

**Comment by cgarciae** [comment]
@sebasarango1180 LGTM, I resolved the conflicts in the README.

**Comment by cgarciae** [comment]
@sebasarango1180 good to go?

**Pull request merged**
